### ISSUE TITLE
Weird highlighting with LaTeX

### ISSUE THREAD

**Issue by frangkli** [rhysd/vim-grammarous#89]
I just installed this plugin and tried it in my latex file. The grammar check works wonderfully but the underline and highlighting of mistakes seem to be off. The space before the word is highlighted and underlined while the last character of the word is not highlighted nor underlined.

Illustration: **_lore**m
Expected: **lorem**
(Bold means highlighted and underlined)

I was thinking this might be a problem with conceal or specifically tex conceal? Any ideas for fix?

**Comment by matze-dd** [comment]
I encounter a possibly related issue with German texts containing German "Umlauts" like 'Ä'.
It seems to me that there is a problem with UTF-8 encoded (or other non-ASCII) texts, since byte and character offsets may differ in this case.
If a line contains a non-ASCII character in the part before the spelling error, highlighting of the error is shifted.

**Comment by FrankLA0203** [comment]
> If a line contains a non-ASCII character in the part before the spelling error, highlighting of the error is shifted.

Yeah that might be it because I had directional quotes (not " but double quotes with directions like what is rendered in latex with `` and '') which could have caused the problem.

**Comment by matze-dd** [comment]
The alternative plugin [\[vim-LanguageTool\]](https://github.com/dpelle/vim-LanguageTool) does not exhibit this problem. However, you cannot continue editing while LanguageTool is running.
Interestingly, [\[ALE\]](https://github.com/dense-analysis/ale) that focuses on asynchronous checks and also has a LanguageTool interface, seems to know the same issue as vim-grammarous.
